apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${jsondecode(template_vars.objects["issuer"]).name}
spec:
  acme:
    email: ${jsondecode(template_vars.objects["issuer"]).email}
    server: ${jsondecode(template_vars.objects["issuer"]).server}
    privateKeySecretRef:
      name: ${jsondecode(template_vars.objects["issuer"]).secretRef}
    solvers:
      - dns01:
          route53:
            region: ${jsondecode(template_vars.objects["issuer"]).region}
            hostedZoneID: ${jsondecode(template_vars.objects["issuer"]).zoneId}
