apiVersion: v1
kind: Secret
metadata:
  name: aws-eks-charts
  namespace: ${argo_namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "aws-eks-charts"
  type: "helm"
  url: "https://aws.github.io/eks-charts"
  project: "${project_name}"
