apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler
  namespace: ${argo_namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "cluster-autoscaler"
  type: "helm"
  url: "https://kubernetes.github.io/autoscaler"
  project: "${project_name}"
