apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: ${template_vars.argo_namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "external-dns"
  type: "helm"
  url: "https://kubernetes-sigs.github.io/external-dns/"
  project: "${template_vars.project_name}"
