apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: ${argo_namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "external-dns"
  type: "helm"
  url: "https://kubernetes-sigs.github.io/external-dns/"
  project: "${project_name}"
