apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress-controller
  namespace: ${template_vars.argo_namespace}

  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "nginx-ingress-controller"
  type: "helm"
  url: "https://kubernetes.github.io/ingress-nginx"
  project: "${template_vars.project_name}"
