apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${template_vars.apps["certmanager"].name}
  namespace: ${template_vars.argo_namespace}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}  # Dynamically generate applications for each cluster in the Argo CD managed clusters
  template:
    metadata:
      name: '{{.name}}-${template_vars.apps["certmanager"].name}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: ${template_vars.project_name}
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.16.2
        helm:
          values: '${jsonencode(yamldecode(template_vars.apps["certmanager"].values))}'
      destination:
        server: "{{.server}}"
        namespace: ${template_vars.apps["certmanager"].namespace}
      syncPolicy:
        automated:
          prune: true  # Automatically prune outdated resources
          selfHeal: true  # Auto-heal if the state is out of sync
        syncOptions:
          - CreateNamespace=true
          - Retry=10
          - Timeout=180
