apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${template_vars.apps["external_dns"].name}
  namespace: ${template_vars.argo_namespace}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}  # Dynamically generate applications for each cluster in the Argo CD managed clusters
  template:
    metadata:
      name: '{{.name}}-${template_vars.apps["external_dns"].name}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: ${template_vars.project_name}
      source:
        repoURL: https://kubernetes-sigs.github.io/external-dns
        chart: external-dns
        targetRevision: 1.14.3
        helm:
          values: '${jsonencode(yamldecode(template_vars.apps["external_dns"].values))}'
      destination:
        server: "{{.server}}"
        namespace: ${template_vars.apps["external_dns"].namespace}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Retry=10
          - Timeout=180
